### ISSUE TITLE
Be careful with statically building pages from live DB

### ISSUE THREAD

**Issue by oliverjam** [fac24/week6-asmahan-hallie-peter-maria#35]
Your plant pages are built _statically_ (because you have used `getStaticPaths`/`getStaticProps`). This means these pages will be created at _build_ time—i.e. when you deploy your site. This can be a good optimisation to make loading a page faster, since you don't have to generate the page fresh for every request. However if your data is _dynamic_ then you will end up with stale pages.

In an eCommerce app it is likely the product info in your database could change at any time. A user could buy the last item, an admin could change the price of something etc. These DB changes would not be reflected in the app's pages, since the pages don't get updated until you re-deploy the whole thing.

When you're reading from a DB you almost always want to default to using `getServerSideProps`, since your data could change at any moment, so you want to always fetch it fresh for each user request.

**Comment by joe-dev-public** [comment]
Note also this point made a few times in the "Learn Next.js" guide from Monday:

"In development mode ... **every page** is pre-rendered on **each request** — even for pages that use ``getStaticProps``" 

(paraphrased from this source: https://nextjs.org/learn/basics/data-fetching/two-forms)

I think this means that you could see your site working as expected locally when you ``npm run dev``, but then when you deploy it would suddenly break (if you're using ``getStaticProps`` instead of ``getServerSideProps``.

Assuming I haven't misunderstood, this is just something to watch out for if you ever have an inexplicably broken deployment :)

**Comment by vasystus** [comment]
All done!
